export const APP_SUGERIDO = {
    pdf: "Adobe Acrobat Reader / navegador",
    doc: "Microsoft Word",
    docx: "Microsoft Word",
    xls: "Microsoft Excel",
    xlsx: "Microsoft Excel",
    ppt: "Microsoft PowerPoint",
    pptx: "Microsoft PowerPoint",
    jpg: "Visualizador de imagens",
    jpeg: "Visualizador de imagens",
    png: "Visualizador de imagens",
    gif: "Visualizador de imagens",
    svg: "Navegador / Editor vetorial (Inkscape)",
    mp3: "Player de áudio (Windows Media Player, VLC)",
    wav: "Player de áudio",
    mp4: "Player de vídeo (VLC, Windows Media Player)",
    mkv: "Player de vídeo (VLC, Windows Media Player",
    txt: "Bloco de notas",
    zip: "Compactador de arquivos (WinRAR, 7-Zip)",
    rar: "WinRAR / 7-Zip",
    html: "Navegador",
    js: "Editor de código (VS Code)",
    json: "Editor de código / Navegador",
    csv: "Excel / Google Sheets",
    appimage: "Executável Linux",
    deb: "Executável Linux",
    flatpakref: "Executável Linux (Flatpak)",
    ttf: "Fontes",

}